import type { Language } from "./types";

export type Signal = [pattern: RegExp, weight: number];

export const SIGNALS = {
  js: [
    [/^\s*(?:export\s+)?(?:const|let|var)\s+[\w${[]+.*=/, 2],
    [/^\s*(?:export\s+)?(?:async\s+)?function\b\s*\*?\s*[\w$]*\s*\(/, 2],
    [/^\s*import\s+(?:[\w*${},\s]+\s+from\s+)?["'][^"']+["']/, 2],
    [/^\s*export\s+(?:default|const|let|function|class|async)\b/, 2],
    [/\brequire\(\s*["'][^"']+["']\s*\)/, 2],
    [/\bmodule\.exports\b/, 2],
    [/\bconsole\.(?:log|warn|error|info)\(/, 1],
    [/=>\s*[{(\w]/, 1],
    [/\b(?:document|window)\.[a-zA-Z]+/, 1],
    [/^\s*(?:export\s+)?class\s+\w+(?:\s+extends\s+\w+)?\s*\{/, 1],
  ],
  ts: [
    [/^\s*(?:export\s+)?(?:declare\s+)?(?:interface|type)\s+[A-Z]\w*\s*(?:<[^>]*>)?\s*(?:=|\{|extends)/, 3],
    [/^\s*(?:export\s+)?(?:const\s+)?enum\s+\w+\s*\{/, 3],
    [/[):]\s*(?:string|number|boolean|void|unknown|never)\b(?:\[\])?\s*[,;=){|]/, 2],
    [/\bas\s+(?:const|unknown|string|number)\b/, 1],
    [/\b(?:private|public|protected|readonly)\s+\w+\s*[:(]/, 1],
    [/\bimplements\s+\w+/, 1],
    [/^\s*import\s+type\b/, 3],
  ],
  c: [
    [/^\s*#\s*include\s*[<"][^>"]+[>"]/, 3],
    [/^\s*#\s*(?:define|ifdef|ifndef|endif|pragma)\b/, 2],
    [/\b(?:int|void)\s+main\s*\(/, 3],
    [/\b(?:printf|scanf|malloc|free|memcpy|strlen)\s*\(/, 1],
    [/^\s*typedef\s+/, 2],
    [/^\s*(?:typedef\s+)?struct\s+\w*\s*\{/, 2],
    [/^\s*(?:static\s+)?(?:unsigned\s+)?(?:int|char|long|short|float|double|size_t)\s+\**\w+\s*(?:\(|=|;)/, 1],
  ],
  cpp: [
    [/\bstd::\w+/, 3],
    [/^\s*using\s+namespace\s+\w+/, 3],
    [/^\s*template\s*<[^>]*>/, 3],
    [/^\s*#\s*include\s*<(?:iostream|vector|string|map|set|memory|algorithm|cstdio|cstdlib|cmath|thread|mutex|optional|functional)>/, 4],
    [/\b(?:nullptr|constexpr|noexcept|static_cast|dynamic_cast|reinterpret_cast)\b/, 2],
    [/\b(?:public|private|protected)\s*:\s*$/, 2],
    [/\b(?:cout|cin|cerr)\s*(?:<<|>>)/, 3],
  ],
  java: [
    [/^\s*package\s+[\w.]+;/, 3],
    [/^\s*import\s+(?:static\s+)?[\w.]+(?:\.\*)?;/, 2],
    [/\bpublic\s+static\s+void\s+main\s*\(/, 4],
    [/\bSystem\.(?:out|err)\.print/, 3],
    [/^\s*(?:public|private|protected)\s+(?:static\s+)?(?:final\s+)?(?:class|interface|enum|record)\s+\w+/, 2],
    [/^\s*@(?:Override|Deprecated|FunctionalInterface|SuppressWarnings)\b/, 2],
    [/\b(?:List|Map|Set|Optional)<\w+(?:,\s*\w+)?>\s+\w+\s*(?:=|;)/, 1],
  ],
  kotlin: [
    [/^\s*fun\s+(?:<[^>]*>\s*)?[\w.]+\s*\(/, 3],
    [/^\s*(?:private\s+|internal\s+)?(?:val|var)\s+\w+\s*(?::\s*[\w<>?]+)?\s*=/, 2],
    [/^\s*(?:data|sealed|open|enum)\s+class\s+\w+/, 3],
    [/^\s*package\s+[\w.]+\s*$/, 2],
    [/^\s*import\s+[\w.]+(?:\.\*)?\s*$/, 1],
    [/\bprintln\(/, 1],
    [/^\s*object\s+\w+/, 2],
  ],
  csharp: [
    [/^\s*using\s+System[\w.]*;/, 4],
    [/^\s*namespace\s+[\w.]+\s*(?:\{|;)?\s*$/, 2],
    [/\bConsole\.Write(?:Line)?\(/, 3],
    [/\b(?:public|private|internal|protected)\s+(?:static\s+)?(?:async\s+)?(?:void|string|int|bool|Task(?:<.*>)?)\s+\w+\s*\(/, 2],
    [/\{\s*get;\s*(?:private\s+)?(?:set;)?\s*\}/, 3],
    [/\bvar\s+\w+\s*=\s*new\s/, 1],
  ],
  python: [
    [/^\s*def\s+\w+\s*\(.*\)\s*(?:->\s*[^:]+)?:\s*$/, 3],
    [/^\s*class\s+\w+(?:\(.*\))?:\s*$/, 3],
    [/^\s*(?:from\s+[\w.]+\s+import\s+\S|import\s+[\w.]+(?:\s+as\s+\w+)?\s*$)/, 2],
    [/^\s*if\s+__name__\s*==/, 4],
    [/^\s*(?:elif\s.+|else|try|finally|except(?:\s.+)?)\s*:\s*$/, 2],
    [/^\s*for\s+\w+(?:\s*,\s*\w+)*\s+in\s+.+:\s*$/, 2],
    [/^\s*with\s+.+\s+as\s+\w+\s*:\s*$/, 2],
    [/^\s*print\(/, 1],
    [/\bself\.\w+/, 1],
  ],
  lua: [
    [/^\s*local\s+\w+(?:\s*,\s*\w+)*\s*=/, 2],
    [/^\s*(?:local\s+)?function\s+[\w.:]+\s*\(/, 3],
    [/^\s*for\s+\w+(?:\s*,\s*\w+)?\s+in\s+i?pairs\(/, 3],
    [/^\s*end\s*[),]?\s*$/, 1],
    [/\bthen\s*$/, 2],
    [/^\s*return\s+function\s*\(/, 1],
  ],
  go: [
    [/^package\s+\w+\s*$/, 4],
    [/^\s*func\s+(?:\(\w+\s+\*?\w+\)\s+)?\w+\s*\(/, 3],
    [/^\s*import\s+(?:\(|")/, 2],
    [/\w\s*:=\s*\S/, 1],
    [/\bfmt\.\w+\(/, 3],
    [/^\s*type\s+\w+\s+(?:struct|interface)\s*\{/, 3],
  ],
  rust: [
    [/^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+\w+\s*(?:<[^>]*>)?\s*\(/, 3],
    [/^\s*use\s+[\w:]+(?:::\{.*\})?;/, 2],
    [/\blet\s+(?:mut\s+)?\w+\s*(?::\s*[^=]+)?=/, 2],
    [/^\s*(?:pub\s+)?(?:struct|enum|trait|impl)\b/, 2],
    [/\b(?:println|vec|format|panic|assert_eq)!\(/, 3],
    [/^\s*#\[derive/, 3],
    [/->\s*(?:Result|Option|Self|&)/, 1],
  ],
  php: [
    [/<\?php/, 4],
    [/^\s*\$\w+\s*=/, 2],
    [/\$this->\w+/, 3],
    [/^\s*(?:public\s+|private\s+|protected\s+)?(?:static\s+)?function\s+\w+\s*\(/, 1],
    [/^\s*(?:namespace|use)\s+[\w\\]+;/, 2],
    [/\b(?:echo|print)\s+["'$]/, 1],
    [/\barray\(/, 1],
  ],
  shell: [
    [/^#!\s*\/(?:usr\/)?bin\/(?:env\s+)?(?:ba|z|da)?sh\b/, 4],
    [/^\s*(?:if|elif)\s+\[\[?\s.*\]\]?\s*;?\s*then\s*$/, 3],
    [/^\s*for\s+\w+\s+in\s+.*;\s*do\s*$/, 3],
    [/^\s*(?:fi|done|esac)\s*$/, 1],
    [/^\s*\w+\(\)\s*\{\s*$/, 2],
    [/^\s*(?:export|source)\s+[\w./]+/, 1],
    [/^\s*echo\s+["'$]/, 1],
  ],
  sql: [
    [/^\s*select\b.+\bfrom\b/i, 3],
    [/^\s*(?:insert\s+into|update\s+\w+\s+set|delete\s+from|create\s+(?:table|index|view|database)|alter\s+table|drop\s+table)\b/i, 3],
    [/^\s*(?:FROM|WHERE|GROUP BY|ORDER BY|(?:LEFT |INNER )?JOIN)\b/, 1],
    [/^\s*(?:PRIMARY KEY|NOT NULL|VARCHAR\(\d+\))/, 1],
  ],
  html: [
    [/^\s*<!doctype\s+html/i, 4],
    [/<html[\s>]/i, 3],
    [/<\/?(?:head|body|title|meta|link|script|style)[\s>/]/i, 2],
    [/<\/?(?:div|span|p|a|ul|ol|li|h[1-6]|img|table|tr|td|th|form|input|button|section|nav|footer|header|main|br|hr|label|select|option|textarea|iframe)[\s>/]/i, 2],
  ],
  xml: [
    [/^\s*<\?xml\b/, 4],
    [/\bxmlns(?::\w+)?=/, 2],
    [/^\s*<!\[CDATA\[/, 2],
    [/^\s*<[A-Za-z_][\w.:-]*(?:\s+[\w.:-]+\s*=\s*(?:"[^"]*"|'[^']*'))*\s*\/?>\s*$/, 1],
    [/<\/[A-Za-z_][\w.:-]*>\s*$/, 1],
  ],
  css: [
    [/^\s*@(?:media|import|font-face|keyframes|charset|supports|layer|container)\b/, 3],
    [/^\s*(?:[.#*:][\w-]*(?:[\s>+~,.#:[][\w\s.#:>+~,[\]="'*-]*)?|(?:html|body|a|p|h[1-6]|ul|li|div|span|img|button|input|table|nav|header|footer|main|section))\s*\{\s*$/, 2],
    [/^\s*--[\w-]+\s*:\s*\S/, 2],
    [/^\s*(?:color|background(?:-[a-z]+)?|margin(?:-[a-z]+)?|padding(?:-[a-z]+)?|display|position|width|height|(?:min|max)-(?:width|height)|font(?:-[a-z]+)?|border(?:-[a-z-]+)?|text-[a-z-]+|line-height|flex(?:-[a-z]+)?|grid(?:-[a-z-]+)?|align-[a-z-]+|justify-[a-z-]+|gap|z-index|opacity|overflow(?:-[xy])?|cursor|transition(?:-[a-z]+)?|transform|box-shadow)\s*:(?!\s*(?:string|number|boolean|any)\b)\s*[^;{]+;?\s*(?:\/\*.*)?$/, 2],
  ],
  ini: [
    [/^\s*\[[^\]\n]+\]\s*$/, 2],
    [/^\s*[\w.-]+\s*=\s*\S/, 1],
    [/^\s*;/, 1],
  ],
  diff: [],
  csv: [],
} satisfies Record<Language, Signal[]>;

